config/routes.rb
Rails.application.routes.draw do

  get 'about/index', as: 'about'

  get 'about/resume'

  get 'static_page/home'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories, :posts

  get 'static_page/home'

  root 'static_page#home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category

  has_attached_file :image, styles: {
    thumb: "150x150>",
    medium: "300x300>",
    large: "600x600>"
  }
  validates_attachment_presence :image
  validates_attachment_size :image, less_than: 2.megabytes
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_attachment_file_name :image, matches: [/png\z/, /jpe?g\z/]
  validates_uniqueness_of :image_file_name

  validates :title, presence: true, uniqueness: true


end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all  
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :fetch_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @post }
    end
  end

  def new
    @post = Post.new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def post_params
    params.require(:posts).permit()
  end
  def fetch_post
    @post = Post.find(params[:id])
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/about/index.html.erb
<div class="container nav_fit">


        <div id="about">
          <div class="col-md-9">
            <div class="well">
            <div class="page-header">
              <!-- <h1>Chinyere Odinukwe</h1> -->
            </div> <!-- end page-header -->

            <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#demo-collapse">ARTIST BIO</button>

            <!--<div id="demo-collapse" class="collapse in">
              <p>The Artist is the one who forms the beauty, pain, sorrow, joys, and innumerable human experiences in the mix of pain and brush</p>
            </div>  end collapse -->

            <hr>

            <p class="text-justify">
              Chinyere Odinukwe is a mid-career multi-disciplinary artist armed with a Master of Fine Arts  in painting from the University of Nigeria Nsukka. Her recent corpus of works interrogate patriotism, national identity, culture, communal awareness, insecurity, politics and societal norms on both personal and social levels, her works attempt to delve into the mind of individuals and communities to bring to bear, what their agendas might birth if it was visual.
              Her paintings portray a dramatic kaleidoscope of vibrant warm and complimentary colours  which is also reminiscent of the environmental and global issues she's been faced with in recent times as she struggles to let out the dramatic aspect of her that is concerned about human and environmental sustenance in the long run.
              Her techniques juxtapose domestic and industrial waste materials such as plastics, aluminium products, salvaged Aluminium foil paper, cellophane bags as well as a long list of items that occupy and litter her environment, she agrees with reducing ecological hazard and environmental degradation by using these items to form art and making a strong statement in the process. She has participated in several art exhibitions, workshops and residency program. She currently lives and works in Abuja, Nigeria.
            </p>

            <!-- <a href="#">EMAIL</a> -->
            <%= link_to "RESUME", about_resume_path %>
            </div>
          </div> <!-- end col-md-9 -->


          <div class="col-md-3">
            <img src="<%# asset_path('chinyereOd.png') %>" width="190px"/>
          </div> <!-- end col-md-3 -->
        </div>


      <hr />

      <!--<div id="contact">
        <div class="col-sm-3 col-sm-offset-0">
          <h3 class="page-header">Contact Me</h3>
          <div class="well well1">
          <form role="form" >
            <div class="form-group">
              <label for="name">Name</label>
              <input type="text" class="form-control" id="name" placeholder="Enter name" />
            </div>
            <div class="form-group">
              <label for="email">Email</label>
              <input type="email" class="form-control" id="email" placeholder="Enter email" />
            </div>
            <div class="form-group">
              <label for="message">Message</label>
              <textarea class="form-control" id="message" placeholder="Enter message" ></textarea>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          </div>
        </div>
      </div>-->


    </div> <!-- end container -->

app/views/about/resume.html.erb
<div class="container nav_fit">
      <div class="row">

        <div class="col-md-9">
          <div class="well">
          <div class="page-header">
            <h1>Professional Information</h1>
            <p class="text-justify">
              Much like all artists claim, I have always enjoyed drawing and creating. After attending the Academy I rediscovered a love of kid's books and entertainment. My art has always been very stylized and simple, working mainly with bold shapes and funny expressions. I draw things that make me laugh, typically animals, robots and kids. My biggest joy is that when people see my work, it at the very least makes them smile.
            </p>
          </div> <!-- end page-header -->

          <div class="page-header">
            <h1>Work Experience</h1>
            <h4 class="panel-title">Real Escape Game -Set Designer​ 2013 - present
            </h4>
            <small class="panel-body">
              Recently graduated from the Academy with my Master's Degree this past Spring. I focused in Children's Book illustration and Visual Development
            </small>

            <h4 class="panel-title">Real Escape Game -Set Designer​ 2013 - present
            </h4>
            <small class="panel-body">
              Recently graduated from the Academy with my Master's Degree this past Spring. I focused in Children's Book illustration and Visual Development
            </small>

          </div> <!-- end page-header -->

          <div class="page-header">
            <h1>Education</h1>
            <h4 class="panel-title">Academy of Art University - MFA Program ​2009 - 2012
            </h4>
            <small class="panel-body">
              Designing and building real life puzzle rooms for a live-action game company.
            </small>

            <h4 class="panel-title">Academy of Art University - BSC Program ​2009 - 2012
            </h4>
            <small class="panel-body">
              Designing and building real life puzzle rooms for a live-action game company.
            </small>

            <h4 class="panel-title">Regina Pacis Girls Secondary School - WAEC Program ​2009 - 2012
            </h4>
            <small class="panel-body">
              Designing and building real life puzzle rooms for a live-action game company.
            </small>
          </div> <!-- end page-header -->
        </div>
        </div> <!-- end col-md-9 -->


        <div class="col-md-3">
          <div class="page-header">
            <h4>Skills</h4>
          </div>
          <div class="list-group">
            <small class="list-group-item">Painting</small>
            <small class="list-group-item">Graphics</small>
            <small class="list-group-item">Video Editing</small>
            <small class="list-group-item">Photoshop</small>
            <small class="list-group-item">Illustrator</small>
            <small class="list-group-item">Tie and Dye</small>
          </div>
        </div> <!-- end col-md-3 -->


      </div> <!-- end row -->
    </div> <!-- end container -->

app/views/categories/index.html.erb
<div class="container nav_fit">
  <h2>Posts Categrories</h2>
  <ul>
    <% @categories.each do |category| %>
    <li><%= link_to category.name, category %> (<%= category.posts.count %>)</li>
    <% end %>
  </ul>
</div>

app/views/categories/show.html.erb
<div class="container nav_fit">
  <h2><%= @category.name %></h2>

  <ul>
    <% @category.posts.each do |post| %>
    <li><%= link_to post.title, post %></li>
    <% end %>
  </ul>

  <p><%= link_to "Back to Post Categories", categories_path %></p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Artz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'partials/header' %>

  <div class="container">
      <div class="row">
        <div class="col-md-8">
          <% if flash[:notice] %>
            <div class="alert alert-success">
              <%= flash[:notice] %></div>
          <% end %>

          <% if flash[:alert] %>
            <div class="alert alert-danger"><%= flash[:alert] %></div>
          <% end %>
        </div>
      </div>
    </div>
    <%= yield %>

  <%= render 'partials/footer' %>

</body>
</html>

app/views/partials/_footer.html.erb
<section id="footer">
  <div class="container">
    <div class="row">
      <p class="col-md-6">
        &copy; ChinyereOd <%= Time.now.year %>
        <%# Date.current.year %>
        <%# Time.zone.now.year %>
      </p>
      <div class="col-md-6">
        <ul class="list-inline" style="margin-left:2px!important;">
          <a href="https://www.facebook.com/chinyere.od" ><i class="fa fa-facebook-square"></i></a>
          <a href="#" ><i class="fa fa-twitter-square"></i></a>
          <a href="#" ><i class="fa fa-google-plus-square"></i></a>
          <a href="#" ><i class="fa fa-instagram"></i></a>
        </ul>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </p>
      </div>
      <div class="col-md-6">
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </p>
      </div>
    </div>
  </div>
</section>

app/views/partials/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'chinyereOd', root_path, class: 'navbar-brand' %>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="themes">Works <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="themes">
                <li><%= link_to 'Arts', posts_path %></li>
                <li><a href="./cerulean/">Articles</a></li>
                <li><a href="./cyborg/">Design</a></li>
                <li><a href="./darkly/">Graphics</a></li>
              </ul>
            </li>
            <li><a href="#">Exhibitions</a></li>
            <li><a href="#">Media</a></li>
            <li>
              <%= link_to 'About', about_path %>
            </li>
          </ul>

<!--
          <ul class="nav navbar-nav navbar-right">
            <li><a href="" target="_blank">Short Stories</a></li>
            <li><a href="" target="_blank">Sketches</a></li>
          </ul>
-->

        </div>
      </div>
    </div>

app/views/posts/index.html.erb
<!-- <div class="nav_fit">
  <%# @posts.each do |post| %>
    <div class="product">
      <%# link_to image_tag( post.image), post_path(post) %>
      <h2><%# link_to post.title, post_path(post) %></h2>
    </div>
  <%# end %>

  <div style="clear:both"></div>
</div> -->
<section class="art-coll">
  <div class="row">
    <h3>Collections of my paintings</h3>
    <p class="sub-coll">my paintings tells about my experiences</p>
    <p class="brush">
      <i class="fa fa-paint-brush" aria-hidden="true"></i>
    </p>
  </div>
</section>

<div class="container nav_fit">
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-sm-6 col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag( post.image), post_path(post) %>
          <h2><%= link_to post.title, post_path(post) %></h2>
          <%# link_to (image_tag post.image.url(:medium), class: 'image'), post %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<%# if @post.image? %>
  <!-- <p>This art is done</p> -->
<%# else %>
    <!-- <p>This art is still in developments</p> -->
<%# end %>



<!-- <div class="post-description">
  <% if @post.description %>
    <%= simple_format @post.description %>
  <% else %>
    <p><em>No Description</em></p>
  <% end %>

  <p>
    <strong>Title:</strong>
    <%= @post.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @post.description %>
  </p>

  <p>
    <strong>Measuremnt:</strong>
    <%= @post.measurement %>
  </p>

  <p>
    <strong>Artist:</strong>
    <%= @post.artist %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @post.category %>
  </p>
</div> -->


<div class="container nav_fit">

  <h2><%= @post.title %></h2>

  <%= image_tag @post.image, :id => "post-image" %>
  <div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%# image_tag @post.image.url(:medium) %>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @post.title %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @post.description %></td>
              </tr>
              <tr>
                <td><strong>Measurement:</strong></td>
                <td><%= @post.measurement %></td>
              </tr>
              <tr>
                <td><strong>Artist:</strong></td>
                <td><%= @post.artist %></td>
              </tr>
              <tr>
                <td><strong>Category:</strong></td>
                <td><%= @post.category %></td>
              </tr>
            </tbody>
          </table>
        </div>
        <%# link_to 'Edit', edit_art_path(@post), class: "btn btn-default" %>
        <%= link_to 'Back', post_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/static_page/home.html.erb
    <!-- Carousel
    ================================================== -->
<!--
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
       Indicators
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="<%# asset_path('WP_20170327_11_50_07_Pro.jpg') %>" width="190px"/>
          <div class="container">
            <div class="carousel-caption">
              <h1>Clad in spoils</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="<%# asset_path('WP_20170327_11_50_40_Pro.jpg') %>" width="190px"/>
          <div class="container">
            <div class="carousel-caption">
              <h1>tears of the night</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="<%# asset_path('WP_20170327_12_00_14_Pro.jpg') %>" width="190px"/>
          <div class="container">
            <div class="carousel-caption">
              <h1>Nested bird</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <i class="fa fa-chevron-left" aria-hidden="true" style="margin-top:250px;"></i>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="fa fa-chevron-right" aria-hidden="true" style="margin-top:250px;"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
-->
<!-- /.carousel -->
		<div class="jumbotron">
			<img src="<% asset_path('chinyereOd2.jpg') %>" width="100%">
		</div>

		<section class="top-sec">
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<h1 class="intro">chinyere Od is
							<span class="txt-rotate" data-period="2000" data-rotate='[ "an Artist.", "a Writer.", "a Designer.",  "fun!" ]'>
							</span>
						</h1>
						<h4 class="intro-end">art made with <i class="fa fa-heart red" style="color: #BC0213;"></i></h4>
					</div>
					<div class="col-sm-6">
						<h5 class="intro-end">ABOUT</h5>
						<p></p>
						<p></p>
						<p class="about-para">
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
						</p>
						<p></p>
						<p class="about-para">
							Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
						</p>
					</div>
				</div>
			</div>
			<div class="container">
				<div class="row">
					<p class="text-center sub">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
				</div>
			</div>
		</section>

		<section class="top-sec">
			<div class="container">
				<div class="row">
					<h2 class="exhibits">Featured</h2>
					<h2 class="collab">Exhibitons and Collaborations</h2>
					<div class="col-sm-5">
						<h3>
							<span id="event"> UNN AT 50 - Sights and Sounds</span>
						</h3>
						<img src="<%= asset_path('212.jpg') %>" width="100%"/>
					</div>
					<div class="col-sm-5">
						<h3>
							<span id="event"> SACRED FLAGS & CLOTHS</span>
						</h3>
						<img src="<%= asset_path('213.jpg') %>" width="100%"/>
					</div>
<!--
					<div class="col-sm-4">
						<h3>
							<span id="event"> LINKS - to the past</span>
						</h3>
						<img src="<%# asset_path('214.jpg') %>" width="100%"/>
					</div>
-->
				</div>
			</div>
		</section>

		<section class="top-sec">
			<div class="container">
				<div class="row">
					<h2 class="text-center collab">ART EXPRESSION</h2>

				</div>
			</div>
		</section>

    <section id="mapnext" class="section-tw mapnext bg_gradient">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-7 col-md-6">
					<h2 class="section">Lorem Ipsum</h2>
					<h3>Abstractus Decorum</h3>
					<p>Lorem ipsum magnus decorum alpha liberatum expressum infinitum edestrano filipinatus indentus</p>

					<h3>Sagentum Brocconoiti</h3>
					<p>Lorem ipsum magnus decorum alpha liberatum expressum infinitum edestrano filipinatus indentus</p>

					<h3>Macmanimus Solistary</h3>
					<p>Lorem ipsum magnus decorum alpha liberatum expressum infinitum edestrano filipinatus indentus</p>

					<h3>Abstractus Decorum</h3>
					<p>Lorem ipsum magnus decorum alpha liberatum expressum infinitum edestrano filipinatus indentus</p>
				</div>

				<div class="col-xs-12 col-sm-5 col-md-6">

				</div>
			</div>
		</div>
	</section>

	<section>

	</section>